feat: Move, Copy, Delete, Update, Rename files
kysect/CentumFramework pull request #10
Opened 2021-06-22 11:27 UTC by ronimizy

2021-06-22 15:50 UTC, FrediKats commented on CentumFramework/GoogleDrive/DriveFile.cs
> +        public DriveFile Move(IEnumerable<string> from, IEnumerable<string> to,
А почему  from - это лист строк?

2021-06-22 15:50 UTC, FrediKats commented on CentumFramework/GoogleDrive/GoogleDriveService.cs
> +            => UpdateFile(file, new HashSet<FileField> {FileField.Parents}, additionalBody, r =>
Мне не очень нравится, что у тебя аргументы переносятся как-то хаотично. Лучше тогда уже писать их в столбик, один за одним.

2021-06-22 16:38 UTC, ronimizy commented on CentumFramework/GoogleDrive/DriveFile.cs
> +        public DriveFile Move(IEnumerable<string> from, IEnumerable<string> to,
Потому что File в апи гугл диска имеет нескольких родителей

2021-06-23 16:24 UTC, ronimizy commented
1. Добавил функции Delete, Update, Rename
Функция Update обновляет заданные поля у файла
2. Поменял переносы строк

2021-06-24 18:40 UTC, s4xack commented on CentumFramework/GoogleDrive/DriveFile.cs
> +        public DriveFile Move(IEnumerable<string> from, IEnumerable<string> to,
![image](https://user-images.githubusercontent.com/35222382/123315828-d4321600-d534-11eb-848a-9f5bbcd19e41.png)

2021-06-24 18:44 UTC, s4xack requested changes

2021-06-24 18:44 UTC, s4xack commented on CentumFramework/GoogleDrive/DriveFile.cs
> +        }
я бы из второго вызывал первый конструктор и в Parents передавал пустой список. Аналогичное и с третьим

2021-06-25 08:17 UTC, ronimizy commented on CentumFramework/GoogleDrive/DriveFile.cs
> +        public DriveFile Move(IEnumerable<string> from, IEnumerable<string> to,
UPD: Я тут разрсёрчил, Гугл дропнули поддержку нескольких родителей, но в АПИ всё ещё оставили возможность это делать (гении), так что поменяю сейчас)

2021-06-25 09:13 UTC, ronimizy commented on CentumFramework/GoogleDrive/DriveFile.cs
> +        }
На данный момент нужен только один конструктор, так что не актуально

2021-06-25 09:18 UTC, ronimizy commented
1. Добавил класс Папки
> Поддерживает функционал смены цвета папки на диске
2. Заменил базовые вызовы функций взаимодействия (те, что не требуют дополнительных гугловских тел вызовов) на авто поля
3. Добавил новые поля файла 

На данный момент думаю стоит прекратить добавлять фичи в эту ветку)

2021-06-26 20:57 UTC, I-SER-I approved these changes

2021-06-26 20:59 UTC, merged