Features
kysect/CentumFramework pull request #16
Opened 2021-07-05 14:54 UTC by ronimizy

2021-07-06 08:29 UTC, hrrrrustic reviewed
В тестах очень много дифа на просто добавление пустой строки, отписался по мелочи, в целом вроде ок

2021-07-06 08:29 UTC, hrrrrustic commented on CentumFramework.Tests/GoogleSheetsServiceTests.cs
> +            Assert.Fail();
Симс лайк 
```C#
Assert.Throws<NotMergedRangeException>(() => sheet.UnmergeRange(rangeThree);
```

2021-07-06 08:29 UTC, hrrrrustic commented on CentumFramework.sln.DotSettings.user
> +
Это вообще что? Уверен, что это не какие-то локальные настройки?

2021-07-06 08:29 UTC, hrrrrustic commented on CentumFramework/GoogleAuthorisation/GoogleAuthorisationService.cs
> +            _scopes = scopes.ToList();
```suggestion
        private readonly IReadOnlyCollection<Scope> _scopes;
        

        public GoogleAuthorisationService(string username, string secretsInputPath, string tokenOutputPath, ICollection<Scope> scopes)
        {
            _username = username;
            _inputPath = secretsInputPath;
            _outputPath = tokenOutputPath;
            _scopes = scopes;
```

2021-07-06 08:29 UTC, hrrrrustic commented on CentumFramework/GoogleAuthorisation/GoogleAuthorisationService.cs
> +            _scopes = scopes.ToList();
Лист это конечно круто, но он тебе явно не нужен тут

2021-07-06 08:29 UTC, hrrrrustic commented on CentumFramework/GoogleAuthorisation/GoogleAuthorisationService.cs
> +                return _credential;
Слишком много для геттера

2021-07-06 08:29 UTC, hrrrrustic commented on CentumFramework/GoogleAuthorisation/GoogleAuthorisationService.cs
> +                        return _credential;
Я так понимаю это должно быть синглтоном?
Обычно делают две проверки на null. Одну перед локом, а другую внутри. Зачем - почитаешь, расскажешь

2021-07-06 08:29 UTC, hrrrrustic commented on CentumFramework/GoogleAuthorisation/GoogleAuthorisationService.cs
> +                new FileDataStore(outputPath, true)).Result;
Я так понимаю, с async/await не знаком, поэтому пока ок
Но в целом .Result не оч

2021-07-06 08:29 UTC, hrrrrustic commented on CentumFramework/GoogleSheets/Entities/Sheet.cs
> +            }
имхо опять тяжеловато для get/set

2021-07-06 08:29 UTC, hrrrrustic commented on CentumFramework/GoogleSheets/Entities/Sheet.cs
> +                            values[i].Add(null);
Я не особо понимаю в целом какую-то архитектуру и флоу кода
Но
а) А шо здесь вообще происходит? О.о Ты просто дописываешь в конце каждой строки `null`ы?
б) А в чем смысл в итоге возвращать `IEnumerable`, если можно `IList`?

2021-07-06 08:29 UTC, hrrrrustic commented on CentumFramework/GoogleSheets/Models/Exceptions/NotMergedRangeException.cs
> +    [Serializable]
А зачем этот атрибут, если не секрет?

2021-07-06 08:29 UTC, hrrrrustic commented on CentumFramework/GoogleSheets/Models/MergeType.cs
> +        Rows
```suggestion
        All = 1,
        [StringValue("MERGE_COLUMNS")]
        Columns = 2,
        [StringValue("MERGE_ROWS")]
        Rows = 3
```

Если не указывать явно, то енам начнется с 0 => в любой непонятной ситуации, когда енам проинициализируется дефолтным для структур значением (0), ты будешь думать, что все ок и значение All. Хотя на самом деле там может вообще полпроекта умерло

2021-07-06 08:29 UTC, hrrrrustic commented on CentumFramework/GoogleSheets/Models/PasteOrientation.cs
> +        Transposed
Сейм, указывай значения явно
Хотя бы для первого = 1 (дальше само проставится), но лучше всем

2021-07-06 08:29 UTC, hrrrrustic commented on CentumFramework/GoogleSheets/Models/SheetField.cs
>          FrozenColumnCount,
в дифе не видно что это, но полагаю опять енам, сейм просто значения

2021-07-06 08:29 UTC, hrrrrustic commented on CentumFramework/appsettings.json
> -        "Username" : "user"
А почему это удалилось? Откуда теперь креды берутся? (чот просто по дифу не заметил)

2021-07-06 08:29 UTC, hrrrrustic commented on CentumFramework/GoogleAuthorisation/Scopes.cs
> +        Drive
опять енам

2021-07-06 08:47 UTC, ronimizy commented on CentumFramework/GoogleAuthorisation/GoogleAuthorisationService.cs
> +                        return _credential;
Чтобы лишний раз замки не занимать, так как делается это медленней чем просто вернуть значение

2021-07-06 09:01 UTC, ronimizy commented on CentumFramework/GoogleSheets/Entities/Sheet.cs
> +                            values[i].Add(null);
a) Да, если пользователь запросил прямоугольник значений - он должен получить прямоугольник значений
b) Я начала делал ```IList``` но райдер сказал переделывать на ```IEnumerable```

2021-07-06 09:02 UTC, ronimizy commented on CentumFramework/appsettings.json
> -        "Username" : "user"
Теперь эти значения передаются в конструктор ```GoogleAuthorizationService```

2021-07-06 09:03 UTC, hrrrrustic commented on CentumFramework/GoogleSheets/Entities/Sheet.cs
> +                            values[i].Add(null);
а) А, ну ок, но вообще мейби есть смысл сделать какой-нибудь пустой объект, чтобы уж прям null не пихать cc: @FrediKats 
б) Ну это классика ) Хз кстати можно ли его попросить не задалбывать этим

2021-07-06 09:05 UTC, ronimizy commented on CentumFramework/GoogleSheets/Models/Exceptions/NotMergedRangeException.cs
> +    [Serializable]
Если не указывать его, sonarcloud ругается, говорит пахнет

2021-07-06 09:12 UTC, hrrrrustic commented on CentumFramework/GoogleSheets/Models/Exceptions/NotMergedRangeException.cs
> +    [Serializable]
🤔 

Ну ок, пусть будет

2021-07-06 09:16 UTC, ronimizy commented on CentumFramework/GoogleSheets/Entities/Sheet.cs
> +                            values[i].Add(null);
a) Просто ```new object()``` клал мне прогу на ```SheetService:SetStylesForSheetCells``` так как гугл не умеет чисто объект принимать, можно передавать туда пустую строку, но ```null``` как то логичнее по мне

2021-07-06 09:25 UTC, ronimizy commented on CentumFramework/GoogleAuthorisation/GoogleAuthorisationService.cs
> +                    _credential = CredentialLoadingProcess().Result;
Bruh/Not bruh ? В локе нельзя авейтить прост

2021-07-06 09:30 UTC, hrrrrustic commented on CentumFramework/GoogleAuthorisation/GoogleAuthorisationService.cs
> +                    _credential = CredentialLoadingProcess().Result;
Bruh, но пока забей
Тут в целом не оч т.к. в геттере async/await идеологически bruh
Потом как-нибудь, когда будет понимание асинхронищины

2021-07-11 13:22 UTC, FrediKats requested changes

2021-07-11 13:22 UTC, FrediKats commented on CentumFramework/GoogleSheets/Entities/Sheet.cs
> +            List<List<object>> trimmed = values.Cast<List<object>>().ToList();
Это _очень_ плохо. Кастов вообще должно быть минимум, а тут еще и непонятно почему ты решил, что будет все ок.

2021-07-11 13:22 UTC, FrediKats commented on CentumFramework/GoogleSheets/Entities/Sheet.cs
> +        private void SetRangeValues(SheetIndexRange range, IEnumerable<IEnumerable<object>> values)
Если этот метод работает _только_ с листами, то и передавай сюда листы.

2021-07-11 13:22 UTC, FrediKats commented on CentumFramework/GoogleSheets/Models/SheetActions/CopyRangeAction.cs
> +            _destinationRange = new SheetIndexRange(index, (index + range.To - range.From).IncrementedBy(1, 1));
Кажется, тут должен вызываться какой-то из методов SheetIndexRangeExtension.

2021-07-11 13:22 UTC, FrediKats commented on CentumFramework/GoogleSheets/Models/SheetIndex.cs
> +               left.Row < right.Row;
Забавно, что ты реши ввести операторы сравнения на не упорядоченном множестве! (и даже на не частичноупорядоченом)

2021-07-11 13:22 UTC, FrediKats commented on CentumFramework/GoogleSheets/Models/SheetIndexRange.cs
> +
Не работает.
![image](https://user-images.githubusercontent.com/22368203/125196831-fc738180-e263-11eb-9f34-11952ee25486.png)

2021-07-11 14:28 UTC, FrediKats approved these changes

2021-07-11 14:32 UTC, merged