Global Refactor
kysect/CentumFramework pull request #19
Opened 2021-07-16 18:26 UTC by ronimizy

2021-07-18 15:44 UTC, FrediKats commented
![image](https://user-images.githubusercontent.com/22368203/126073491-6209ce86-154c-4b44-a9ef-3c7fe0fc8a5b.png)

2021-07-18 15:51 UTC, ronimizy commented
Это по большей части потому что я по проектам перераскидал)

2021-07-18 17:36 UTC, hrrrrustic reviewed
Посмотрел до середины, дальше не вижу смысла т.к. в целом просто куча однотипных классов для разных команд

Написал пару раз однотипные комменты, потом стало лень. Но мест очень много 
1) Полное отсутствие проверок на null со слабыми попытками в аннотацию с `?`
2) Чрезмерная любовь к IEnumerable<T>. Зачем? В полях тем более не надо, у тебя просто по всему приложению потекло вот это лейзи перечисление, которые вообще не нужно.
3) Оставил коммент по поводу метода Respond. Там точно нельзя сделать дженерик вместо object?

2021-07-18 17:36 UTC, hrrrrustic commented on CentumFramework.Drive/Actions/CopyAction.cs
> +        protected readonly IEnumerable<FileField> _fields;
Не делай поля/свойства IEnumerable

2021-07-18 17:36 UTC, hrrrrustic commented on CentumFramework.Drive/Actions/CopyAction.cs
> +            _body = body ?? new GoogleFile();
А остальные два че на `null` не проверяешь?

2021-07-18 17:36 UTC, hrrrrustic commented on CentumFramework.Drive/Actions/CopyAction.cs
> +            => CustomizeRequest(service.Files.Copy(_body, _file.Id));
null?

2021-07-18 17:36 UTC, hrrrrustic commented on CentumFramework.Drive/Actions/CopyAction.cs
> +            request.Fields = _fields.StringRepresentation();
null?

2021-07-18 17:36 UTC, hrrrrustic commented on CentumFramework.Drive/Actions/CreateAction.cs
> +        protected readonly IEnumerable<FileField> _fields;
не надо IE<T>

2021-07-18 17:36 UTC, hrrrrustic commented on CentumFramework.Drive/Actions/CreateAction.cs
> +            _fields = fields;
null

2021-07-18 17:36 UTC, hrrrrustic commented on CentumFramework.Drive/Actions/CreateAction.cs
> +            => CustomizeRequest(service.Files.Create(_body));
null

2021-07-18 17:36 UTC, hrrrrustic commented on CentumFramework.Drive/Actions/DeleteAction.cs
> +            _file = file;
null

2021-07-18 17:36 UTC, hrrrrustic commented on CentumFramework.Drive/Actions/UpdateActions/ChangeFolderColorAction.cs
> +        public override object? Respond(GoogleFile response, Func<GoogleFile, IEnumerable<FileField>, File> converter)
Почему не дженерик?

2021-07-18 17:36 UTC, hrrrrustic commented on CentumFramework.Drive/Entities/File.cs
> +        public string OriginalName { get; internal set; } = null!;
Это плохо, очень плохо
Если ты используешь ! не потому что компилятор тупой, то ты делаешь что-то не так

2021-07-18 17:36 UTC, hrrrrustic commented on CentumFramework.Drive/Entities/File.cs
> +        public long? ContentSize { get; internal set; }
на кой черт тут гора каких-то интернал сетов?

2021-07-18 17:36 UTC, hrrrrustic commented on CentumFramework.Drive/Entities/File.cs
> +                _parent = (Folder) _service.ExecuteActions(new MoveFileAction(this, value)).Single()!;
Это к вопросу о том, почему этот метод не дженерик

2021-07-18 21:36 UTC, ronimizy commented
@hrrrrustic Из полей ```IEnumerable``` убрал, но в большом количестве методов оно осталось (в приватных или внутренних)

2021-07-18 21:38 UTC, hrrrrustic commented
Ну методы ещё ладно, там вопрос холиварный
Завтра уже посмотрю ещё раз

2021-07-20 10:23 UTC, hrrrrustic reviewed
Оставил по мелочи комментов, тесты не смотрел

Не понял движухи с QueryTerm. Какое-то излишнее наследование как по мне, проще же было экстеншнами написать в пару строк?

2021-07-20 10:23 UTC, hrrrrustic commented on Kysect.CentumFramework.Drive/Actions/Models/ListActionConfiguration.cs
> +    }
Рекорды считаются иммутабелными, а ты сеттеров накидал

2021-07-20 10:23 UTC, hrrrrustic commented on Kysect.CentumFramework.Drive/DriveService.cs
> +                return null;
Не лучше ли тут сделать не nullable аргумент и бросать эксепшн?

2021-07-20 10:23 UTC, hrrrrustic commented on Kysect.CentumFramework.Drive/Models/FileField.cs
> +        TopLevel
```suggestion
        TopLevel = 1
```

2021-07-20 10:23 UTC, hrrrrustic commented on Kysect.CentumFramework.Sheets/Actions/UpdateRequests/CreateSheetRequest.cs
> +        }
Довольно странно, что Create может вернуть null

2021-07-20 10:23 UTC, hrrrrustic commented on Kysect.CentumFramework.Sheets/Models/CellStyle/Enums/Alignment.cs
> +        Left,
```suggestion
        Left = 1,
```

2021-07-20 10:23 UTC, hrrrrustic commented on Kysect.CentumFramework.Sheets/Models/CellStyle/Enums/Alignment.cs
> +        Top,
```suggestion
        Top = 1,
```

2021-07-20 10:23 UTC, hrrrrustic commented on Kysect.CentumFramework.Sheets/Models/CellStyle/Enums/Dimension.cs
> +        Horizontal,
```suggestion
        Horizontal = 1,
```

2021-07-20 10:23 UTC, hrrrrustic commented on Kysect.CentumFramework.Sheets/Models/CellStyle/Enums/LineStyle.cs
> +        None,
```suggestion
        None = 1,
```

2021-07-20 10:23 UTC, hrrrrustic commented on Kysect.CentumFramework.Sheets/Models/CellStyle/Enums/TextWrapping.cs
> +        Overflow,
```suggestion
        Overflow = 1,
```

2021-07-20 10:23 UTC, hrrrrustic commented on Kysect.CentumFramework.Sheets/Models/CellStyle/ICellStyle.cs
> +        TextWrapping TextWrapping { get; set; }
В интерфейсах обычно не пишут сеттеры
Если ты укажешь только геттер (что скорее всего тебе только и надо), то ты можешь потом дописать сеттер в реализации

2021-07-20 10:23 UTC, hrrrrustic commented on Kysect.CentumFramework.Sheets/Models/SheetField.cs
> +        TopLevel,
```suggestion
        TopLevel = 1,
```

2021-07-20 10:23 UTC, hrrrrustic commented on Kysect.CentumFramework.Sheets/Models/SheetIndex.cs
> +
Опять сеттеры в рекордах

2021-07-20 10:23 UTC, hrrrrustic commented on Kysect.CentumFramework.Sheets/Models/SheetIndex.cs
> +            Validate();
А чего не наоборот? Сначала провалидировать, а потом сеттить

2021-07-20 10:23 UTC, hrrrrustic commented on Kysect.CentumFramework.Sheets/Models/SheetIndexRange.cs
> +        public SheetIndex To { get; set; }
сеты в рекорде

2021-07-20 10:23 UTC, hrrrrustic commented on Kysect.CentumFramework.Sheets/Models/SpreadsheetField.cs
> +        TopLevel,
```suggestion
        TopLevel = 1,
```

2021-07-20 10:23 UTC, hrrrrustic commented on Kysect.CentumFramework.Sheets/Models/Validation/Conditions/AbsoluteConditionType.cs
> +        TextIsEmail,
```suggestion
        TextIsEmail = 1,
```

2021-07-20 10:23 UTC, hrrrrustic commented on Kysect.CentumFramework.Sheets/Models/Validation/Conditions/BinaryCondition.cs
> +        private readonly object _second;
Чета как-то ненадежно
Нельзя интерфейсик какой-нибудь IBinaryGoogleOperand с методом ToGoogleOperand() вместо ToString()?

2021-07-20 10:23 UTC, hrrrrustic commented on Kysect.CentumFramework.Sheets/Models/Validation/Conditions/BinaryConditionType.cs
> +        NumberBetween,
```suggestion
        NumberBetween = 1,
```

2021-07-20 10:23 UTC, hrrrrustic commented on Kysect.CentumFramework.Sheets/Models/Validation/Conditions/ListConditionType.cs
> +        OneOfList
```suggestion
        OneOfList = 1
```

2021-07-20 10:23 UTC, hrrrrustic commented on Kysect.CentumFramework.Sheets/Models/Validation/Conditions/UnaryConditionType.cs
> +        NumberGreater,
```suggestion
        NumberGreater = 1,
```

2021-07-20 10:23 UTC, hrrrrustic commented on Kysect.CentumFramework.Sheets/Models/Validation/ValidationProtocol.cs
> +        public bool ShowCustomUi { get; set; }
Зачем тут сеттеры?

2021-07-20 10:25 UTC, ronimizy commented on Kysect.CentumFramework.Drive/DriveService.cs
> +                return null;
Нет, так как у файла может не быть родителя

2021-07-20 11:01 UTC, hrrrrustic commented on Kysect.CentumFramework.Drive/DriveService.cs
> +                return null;
А, тогда ладно

2021-07-20 12:10 UTC, ronimizy commented on Kysect.CentumFramework.Sheets/Models/SheetIndex.cs
> +            Validate();
Потому что валидация происходит по значениям полей класса

2021-07-21 19:01 UTC, hrrrrustic commented on Kysect.CentumFramework.Sheets/Models/SheetIndex.cs
> +            Validate();
Ну можно прокинуть аргументами

2021-07-21 19:04 UTC, hrrrrustic approved these changes
Просматривать заново все енамы желания нет, потом по пути можно если что доправить
init в рекордах все равно хз, я бы вообще оставил только get. Но если там нужен init, то пока ок

Написал в коммента про поменять местами Validate, но это мелочь
В любом случае, если есть еще проблемы, то думаю, что можно потом фиксами лучше, чем в сотый раз тут 3к строк менять 
@FrediKats ptal

2021-07-21 19:05 UTC, ronimizy commented on Kysect.CentumFramework.Sheets/Models/SheetIndex.cs
> +            Validate();
Я чёт подумал, и понял что валидацию можно заменить uint`ом для параметров))

2021-07-21 19:14 UTC, ronimizy commented
@hrrrrustic Без ```init``` не работает ```with```

2021-07-21 19:15 UTC, hrrrrustic commented
А, ну тогда окей

2021-07-21 19:28 UTC, FrediKats requested changes

2021-07-21 19:28 UTC, FrediKats commented on Kysect.CentumFramework.Utility/Extensions/EnumExtension.cs
> +                if (type.AttributeValues<AssociatedStringAttribute>().Single().Value == value)
string.Compare

2021-07-21 19:28 UTC, FrediKats commented on Kysect.CentumFramework.Utility/Extensions/EnumExtension.cs
> +            MemberInfo[] memberInfo = type.GetMember(value.ToString() ?? string.Empty);
А как тут может быть null?

2021-07-21 19:28 UTC, FrediKats commented on Kysect.CentumFramework.Utility/Extensions/EnumExtension.cs
> +            Type type = value.GetType();
Рефлекшен - это очень медленная операция. Лучше кешировать.

2021-07-21 19:28 UTC, FrediKats commented on Kysect.CentumFramework.Utility/AuthorisationService.cs
> +
Перенос лишний.

2021-07-21 19:28 UTC, FrediKats commented on Kysect.CentumFramework.Utility/AuthorisationService.cs
> +            ClientSecrets secrets = (await GoogleClientSecrets.FromStreamAsync(stream)).Secrets;
Стоит вынести логику чтения сикретов. В этот сервис должен предоставляться через конструктор экземпляр провайдера, который уже всё отдаёт. Например, если мы читаем не из файла, а храним всё в сикретах Ажура.

2021-07-21 19:28 UTC, FrediKats commented on Kysect.CentumFramework.Tests.Sheets/SheetsTest.cs
> +        public DriveService DriveService { get; set; } = null!;
А ты точно знаешь, что делает "!"?

2021-07-21 19:28 UTC, FrediKats commented on Kysect.CentumFramework.Sheets/SheetsService.cs
> +            _ = service ?? throw new ArgumentNullException(nameof(service));
Это выглядит очень странно. Если очень хочется в 1 строку писать, то пиши как null guard'ы.

2021-07-21 19:28 UTC, FrediKats commented on Kysect.CentumFramework.Sheets/SheetsService.cs
> +            => actions.Select(a =>
Нет единообразия. Часть методов через стрелочки, вторая - с body.

2021-07-21 19:28 UTC, FrediKats commented on Kysect.CentumFramework.Sheets/Models/Validation/ValidationProtocol.cs
> +    public record ValidationProtocol
Ты точно знаешь, что такое рекорды и как их юзать?

2021-07-21 19:28 UTC, FrediKats commented on Kysect.CentumFramework.Sheets/Models/Validation/Conditions/UnaryCondition.cs
> +                new()
Общественно порицаем этот new

2021-07-21 19:28 UTC, FrediKats commented on Kysect.CentumFramework.Sheets/Models/Validation/Conditions/UnaryCondition.cs
> +        public BooleanCondition ToGoogleBooleanCondition() => new()
И этот.

2021-07-21 19:28 UTC, FrediKats commented on Kysect.CentumFramework.Sheets/Models/SheetIndex.cs
> +            Column = column;
Провалидируй аргументы, а потом инициализируй их.

2021-07-21 19:28 UTC, FrediKats commented on Kysect.CentumFramework.Sheets/Models/SheetIndex.cs
> +            result.Validate();
А зачем, если в конструкторе вызывается?

2021-07-21 19:28 UTC, FrediKats commented on Kysect.CentumFramework.Sheets/Models/Field.cs
> +    }
OfType

2021-07-21 19:28 UTC, FrediKats commented on Kysect.CentumFramework.Sheets/Models/CellStyle/LineConfiguration.cs
> +        public static Border ToBorder(this LineConfiguration configuration) => new()
new...

2021-07-21 19:28 UTC, FrediKats commented on Kysect.CentumFramework.Sheets/Models/CellStyle/Enums/Alignment.cs
> +        Center,
Center = 2

2021-07-21 19:29 UTC, hrrrrustic commented on Kysect.CentumFramework.Utility/Extensions/EnumExtension.cs
> +            MemberInfo[] memberInfo = type.GetMember(value.ToString() ?? string.Empty);
ToString бай дизайн nullable у обджекта )

2021-07-21 20:04 UTC, ronimizy commented on Kysect.CentumFramework.Utility/Extensions/EnumExtension.cs
> +                if (type.AttributeValues<AssociatedStringAttribute>().Single().Value == value)
Зачем?

2021-07-21 20:27 UTC, ronimizy commented on Kysect.CentumFramework.Tests.Sheets/SheetsTest.cs
> +        public DriveService DriveService { get; set; } = null!;
Что-то типа "Компилятор, бро, когда это будут использовать, оно не будет всё ломать, я обо всём позабочусь, так что не беспокойся".
Там ругается, так как значения определены не в конструкторе, а в методе [SetUp],

2021-07-21 21:43 UTC, ronimizy commented on Kysect.CentumFramework.Sheets/Models/SheetIndex.cs
> +            Column = column;
int -> uint

2021-07-22 06:22 UTC, ronimizy reviewed
[Fixed] Шо-то конструкторы не те

2021-07-22 06:22 UTC, ronimizy commented on Kysect.CentumFramework.Tests.Drive/DriveTest.cs
> +            var authorisationService = AuthorisationService.Create(applicationName, "user",
Вызывается неправильный конструктор, сюда нужно передавать FileStream

2021-07-22 06:22 UTC, ronimizy commented on Kysect.CentumFramework.Tests.Sheets/SheetsTest.cs
> +            var authorisationService = AuthorisationService.Create(applicationName, "user",
Вызывается неправильный конструктор, сюда нужно передавать FileStream

2021-07-30 19:04 UTC, FrediKats approved these changes

2021-07-30 19:04 UTC, FrediKats commented on Kysect.CentumFramework.Sheets/Entities/Sheet.cs
> +            for (uint i = range.From.Row; i <= range.To.Row; ++i)
Господи, а зачем?

2021-07-31 11:08 UTC, hrrrrustic commented on Kysect.CentumFramework.Sheets/Entities/Sheet.cs
> +            for (uint i = range.From.Row; i <= range.To.Row; ++i)
Шо б жизнь джиту медом не казалась

2021-07-31 14:50 UTC, merged