feat: async actions
kysect/CentumFramework pull request #23
Opened 2021-08-06 22:05 UTC by ronimizy

refactor: drive actions naming Change -> Set

2021-08-07 06:36 UTC, FrediKats requested changes

2021-08-07 06:36 UTC, FrediKats commented on Kysect.CentumFramework.Drive/DriveService.cs
> +                        .ConfigureAwait(false)).Single();
Поясни за ConfigureAwait(false).

2021-08-07 06:36 UTC, FrediKats commented on Kysect.CentumFramework.Drive/DriveService.cs
> +        public async Task<IEnumerable<File>> GetChildrenAsync([NotNull] Folder folder, [NotNull] HashSet<FileField> inputFields,
Лучше не использовать IEnu,erable, у тебя же там IReadOnlyList возвращается.

2021-08-07 06:36 UTC, FrediKats commented on Kysect.CentumFramework.Drive/Entities/File.cs
> +            => (await Service.ExecuteActionsAsync(cancellationToken, new SetFileStarred(this, starred))
Когда тебе приходится брать в скобочки выражение, чтобы на нём вызывать что-то - это звоночек, что возможно не стоит пытаться всё в одну строку писать)

2021-08-07 06:36 UTC, FrediKats commented on Kysect.CentumFramework.Drive/Entities/File.cs
> +            //That way there will always be a File in response
Может лучше написать как  ///<summary>?

2021-08-07 06:36 UTC, FrediKats commented on Kysect.CentumFramework.Sheets/Entities/Spreadsheet.cs
> +                                  .ConfigureAwait(false)).Single().Single()!;
Выглядит страшно.

2021-08-07 07:12 UTC, ronimizy commented on Kysect.CentumFramework.Drive/DriveService.cs
> +                        .ConfigureAwait(false)).Single();
ConfigureAwait помечает, нужно ли продолжать выполнение на том потоке, на котором оно начиналось

2021-08-07 07:13 UTC, ronimizy commented on Kysect.CentumFramework.Drive/Entities/File.cs
> +            => (await Service.ExecuteActionsAsync(cancellationToken, new SetFileStarred(this, starred))
Инлайны, мои инлайны. О мои инлайны!

2021-08-07 11:41 UTC, ronimizy commented on Kysect.CentumFramework.Drive/Entities/File.cs
> +            //That way there will always be a File in response
Это не документация, а оправдание использования `!` строчкой ниже

2021-08-08 23:01 UTC, ronimizy commented
Прятал перегрузки в регионы, чтобы не мозолили глаза, но в какойт-то момент произошли траблы с форматированием райдера, на некоторых методах он не ставил регионы перегрузок рядом с перегружаемым.

2021-08-09 10:31 UTC, FrediKats requested changes

2021-08-09 10:31 UTC, FrediKats commented on Kysect.CentumFramework.Sheets/Actions/ValuesGetAction.cs
> +                        values[i].Add(null!);
Выглядит как полнейший ад. Ты точно знаешь что и зачем это?

2021-08-09 10:37 UTC, ronimizy commented on Kysect.CentumFramework.Sheets/Actions/ValuesGetAction.cs
> +                        values[i].Add(null!);
Гугл возвращает "обрезанные" массивы, если начиная с какого-то индекса значений нет. Сейчас чёт подумал и понял что пусть лучше пользователь будет решать, нужно ли ему добивать какими-то значениями

2021-08-09 17:51 UTC, hrrrrustic commented on Kysect.CentumFramework.Drive/DriveService.cs
> +                        .ConfigureAwait(false)).Single();
Ну...допустим. А почему false-то тогда?

2021-08-09 17:53 UTC, ronimizy commented on Kysect.CentumFramework.Drive/DriveService.cs
> +                        .ConfigureAwait(false)).Single();
Так как контекст синхронизации не важен в данной ситуации, то можно выиграть в эффективности отказавшись от ожидания его освобождения

2021-08-09 23:19 UTC, hrrrrustic commented on Kysect.CentumFramework.Drive/DriveService.cs
> +                        .ConfigureAwait(false)).Single();
Эхххх, прям вот совсем на грани хоть какой-то отдаленной правильности
Я бы предложил убрать, но оно и правда тут нужно по-хорошему
Поэтому предлагаю вставленные уже оставить, но новые не добавлять - оно **_пока что_** того не стоит

cc: @FrediKats

2021-08-10 06:27 UTC, FrediKats approved these changes

2021-08-10 07:12 UTC, ronimizy commented on Kysect.CentumFramework.Sheets/Actions/ValuesGetAction.cs
> +                        values[i].Add(null!);
Соглашусь, я совсем о другом думал когда это писал, не заметил))

2021-08-10 09:59 UTC, merged