feat: SheetIndex.cs & SheetIndexRange.cs string initialization
kysect/CentumFramework pull request #27
Opened 2021-08-10 18:47 UTC by ronimizy

refactor: (Drive/Sheets)Test.cs -> (Drive/Sheets)TestsBase.cs

Closes #26

2021-08-10 20:36 UTC, annchous requested changes

2021-08-10 20:36 UTC, annchous commented on Kysect.CentumFramework.Sheets/Extensions/StringExtension.cs
> +        }
Можешь посмотреть [тут](https://github.com/kysect/Greenper/blob/master/Greenper.Core/Extensions/ValidationExtensions.cs) и подрезать что-нибудь для валидации индекса колонки, ибо твои проверки сейчас покрывают не все случаи

2021-08-10 20:36 UTC, annchous commented on Kysect.CentumFramework.Sheets/Extensions/StringExtension.cs
> +            result += value[0] - 'A';
Ай, [вот тут](https://github.com/kysect/Greenper/blob/4109a8df94fbb67ef6d6ca29ac74119a0b02fe94/Greenper.Core/Models/ColumnWrapper.cs#L22) без этого сделано, можешь глянуть

2021-08-10 20:36 UTC, annchous commented on Kysect.CentumFramework.Sheets/Extensions/StringExtension.cs
> +                throw new ArgumentException("Inappropriate column string");
Сложное слово какое-то))0
```suggestion
                throw new ArgumentException("Invalid column index");
```

2021-08-10 20:36 UTC, annchous commented on Kysect.CentumFramework.Sheets/Models/SheetIndex.cs
> +        public SheetIndex(string columnString, int row)
То, что оно стринг и так понятно, может, лучше `columnIndex`?

2021-08-10 20:36 UTC, annchous commented on Kysect.CentumFramework.Sheets/Models/SheetIndex.cs
> +        public SheetIndex(string indexString)
Мб `indexRange`?

2021-08-10 20:36 UTC, annchous commented on Kysect.CentumFramework.Sheets/Models/SheetIndex.cs
> +                .First(p => char.IsDigit(p.c)).i;
Совсем ничего не понятно)

2021-08-10 20:36 UTC, annchous commented on Kysect.CentumFramework.Sheets/Models/SheetIndex.cs
> +            ReadOnlySpan<char> span = indexString;
@hrrrrustic

2021-08-10 20:36 UTC, annchous commented on Kysect.CentumFramework.Sheets/Models/SheetIndexRange.cs
> +                   new SheetIndex(rangeString.Split(':')[1])) { }
Два раза Сплит одного и того же 🤔

2021-08-10 20:36 UTC, annchous commented on Kysect.CentumFramework.Sheets/Extensions/StringExtension.cs
> +    internal static class StringExtension
Было бы неплохо добавить какую-нибудь обёртку над этим по типу https://github.com/kysect/Greenper/blob/master/Greenper.Core/Models/ColumnWrapper.cs#L22

2021-08-10 20:47 UTC, ronimizy commented on Kysect.CentumFramework.Sheets/Extensions/StringExtension.cs
> +            result += value[0] - 'A';
А вот там точно правильно выведет на АА (expected: 10, looks like: 11)?

2021-08-10 21:05 UTC, ronimizy commented on Kysect.CentumFramework.Sheets/Extensions/StringExtension.cs
> +        }
Символом индекса колонки могут быть только заглавные буквы латинского алфавита. Какие ещё есть случаи?

2021-08-10 21:06 UTC, ronimizy commented on Kysect.CentumFramework.Sheets/Extensions/StringExtension.cs
> +                throw new ArgumentException("Inappropriate column string");
done

2021-08-10 21:40 UTC, ronimizy commented on Kysect.CentumFramework.Sheets/Models/SheetIndex.cs
> +            ReadOnlySpan<char> span = indexString;
ладно, ладно, я ждал момента когда можно будет заюзать эту штуку, но это был не он...

2021-08-12 19:13 UTC, annchous commented on Kysect.CentumFramework.Sheets/Models/Indices/SheetIndexRange.cs
> +        public SheetIndex To { get; set; }
От сеттеров можно избавиться?

2021-08-12 19:15 UTC, annchous commented on Kysect.CentumFramework.Sheets/Models/Indices/SheetIndexRange.cs
> +            string[] split = range.Split(':');
Мб `split` -> `rangeParts`?

2021-08-12 19:18 UTC, annchous commented on Kysect.CentumFramework.Sheets/Models/Indices/SheetIndex.cs
> +            int columnStartIndex = enumeratedString.First(p => char.IsDigit(p.c)).index;
Это не rowStartIndex?

2021-08-12 19:19 UTC, annchous commented on Kysect.CentumFramework.Sheets/Models/Indices/OneBasedIndex.cs
> +        public string String
Я бы не стала использовать String в качестве имени (как и Int)

2021-08-12 19:21 UTC, annchous commented on Kysect.CentumFramework.Sheets/Models/Indices/ColumnIndex.cs
> +        private static void CheckIfRealColumnIndex(char c)
А почему static?

2021-08-12 19:24 UTC, ronimizy commented on Kysect.CentumFramework.Sheets/Models/Indices/ColumnIndex.cs
> +        private static void CheckIfRealColumnIndex(char c)
Потому что этой функции не нужен доступ ни к каким членам класса

2021-08-12 19:32 UTC, ronimizy commented on Kysect.CentumFramework.Sheets/Models/Indices/SheetIndexRange.cs
> +        public SheetIndex To { get; set; }
по факту

2021-08-12 19:34 UTC, ronimizy commented on Kysect.CentumFramework.Sheets/Models/Indices/SheetIndex.cs
> +            int columnStartIndex = enumeratedString.First(p => char.IsDigit(p.c)).index;
а ведь да..

2021-08-12 19:49 UTC, ronimizy commented on Kysect.CentumFramework.Sheets/Models/Indices/OneBasedIndex.cs
> +        public string String
переделал на explicit касты

2021-08-12 19:51 UTC, ronimizy commented
Так как `Value` в `OneBasedIndex` теперь `readonly`, проблемы с тем, что `GetHashCode` получает непостоянные данные снята. Сделать его `readonly` можно потому что это часть `SheetIndex`, который является неизменяемой записью.

2021-08-12 20:05 UTC, annchous commented on Kysect.CentumFramework.Sheets/Models/Indices/SheetIndexRange.cs
> +    public record SheetIndexRange: IEnumerable<SheetIndex>
Рекорд тут, кажется, ничем не полезен?

2021-08-12 20:09 UTC, ronimizy commented on Kysect.CentumFramework.Sheets/Models/Indices/SheetIndexRange.cs
> +    public record SheetIndexRange: IEnumerable<SheetIndex>
очень даже полезен, всё ради `with`

2021-08-12 20:14 UTC, annchous approved these changes
Спокойной ночи

2021-08-12 20:16 UTC, ronimizy commented
Спасибо, тебе тоже!

2021-08-12 20:16 UTC, merged