feat: open ranges
kysect/CentumFramework pull request #35
Opened 2021-08-19 18:23 UTC by ronimizy

removed: implicit ColumnIndex & RowIndex casts
fix: Sheet[SheetIndexRange] returned 3D grid instead of 2D

Closes #34

2021-08-21 23:19 UTC, I-SER-I commented on Kysect.CentumFramework.Sheets/Models/Indices/ColumnIndex.cs
> +            => char.ToUpper(c) is >= 'A' and <= 'Z';
IsValid

2021-08-21 23:20 UTC, I-SER-I commented on Kysect.CentumFramework.Sheets/Models/Indices/OneBasedIndex.cs
> +            => value > 0;
IsValid

2021-08-21 23:36 UTC, I-SER-I commented on Kysect.CentumFramework.Sheets/Models/Indices/RowIndex.cs
> +            => value == 0 ? string.Empty : value.ToString();
< 0 может прилететь?

2021-08-21 23:37 UTC, I-SER-I commented on Kysect.CentumFramework.Sheets/Models/Indices/RowIndex.cs
> +            => value == 0 ? string.Empty : value.ToString();
Увидел Valid

2021-08-22 23:52 UTC, I-SER-I commented on Kysect.CentumFramework.Sheets/Models/Indices/SheetIndex.cs
> +            left.ThrowIfNotEquallyOpen(right);
Лучше запихнуть эту конструкцию в отдельный метод и вызывать ее 4 раза.

Я бы на самом деле поразмышлял как можно перегрузить оператор с одной сигнатурой используя другой, но чет я сломался, это так чисто на подумать

2021-08-22 23:59 UTC, I-SER-I commented on Kysect.CentumFramework.Sheets/Models/Indices/SheetIndex.cs
> +        }
А почему он должен возвращать `SheetIndex `?

2021-08-23 00:05 UTC, I-SER-I commented on Kysect.CentumFramework.Sheets/Models/Indices/SheetIndexRange.cs
> +            }
Логика в конструкторе....

2021-08-23 00:16 UTC, I-SER-I requested changes
10 ThrowIfNull из 10

2021-08-25 08:30 UTC, hrrrrustic commented
> 10 `ThrowIfNull()` из 10

А могли бы уже до превью подняться и юзать `!!`

2021-08-25 14:27 UTC, ronimizy commented on Kysect.CentumFramework.Sheets/Models/Indices/SheetIndex.cs
> +        }
чтобы чейнить проверки или инлайнить проверку с присваиванием

2021-08-28 07:06 UTC, merged