Refactor field access
kysect/CentumFramework pull request #61
Opened 2021-10-24 11:13 UTC by ronimizy

# Задача
Передача данных между объектами разного типа. 
Гугл апи имеет фичу загрузки части информации о сущностях (через строковое указание конкретных полей). Это помогает оптимизировать расход памяти и нагрузку на сеть. Соответственно данный маппинг так же должен это поддерживать. 

# Проблема предыдущей реализации 
Предыдущая реализация была негибкой и не поддерживала вложенные сложные объекты (ex: Sheet.SheetProperties) и загрузку отдельных полей для сложных объектов содержащихся в коллекции (ex: Spreadsheet.Sheets). 
Ну и в общем было написано страшно и некрасиво. 

# Текущее решение
Логика передачи данных была вынесена в отдельную абстракцию `FieldPathAssigner`. У него есть специфические реализации: для обычных объектов, сложных и коллекций сложных объектов.

## PS
Этот пр об изменениях в `.Utility`, изменения в `.Drive` и `.Sheets` связаны с интеграцией новой системы ассайнеров и небольшим изменением API сущностей, потому что старое мозолило мне глаза и очень сильно засоряло классы сущностей (да, это надо было сделать отдельным пром, урок усвоен). 
Проекты `.Drive` и `.Sheets` в будущем потерпят большой рефакторинг экшенов, так что оценивать их файлы нет смысла, так как они всё равно будут изменены.

2021-10-30 13:36 UTC, I-SER-I commented on Kysect.CentumFramework.Utility/Fields/Attributes/SequenceFieldAttribute.cs
> +        internal IEnumerable<TFrom> Convert<TFrom>(object instance, object value, IEnumerable<FieldPathAssigner<TFrom>> paths)
IReadOlny

2021-10-30 18:29 UTC, FrediKats requested changes

2021-10-30 18:29 UTC, FrediKats commented on Kysect.CentumFramework.Utility/Fields/Factories/Assigner.cs
> +                .Select(From);
У тебя assigners остается действительно IE и может несколько раз пересчитываться, если кто-то решит несколько раз пройти. Уверен, что тут стоит его оставить?

2021-10-30 18:29 UTC, FrediKats commented on Kysect.CentumFramework.Utility/Fields/Factories/Assigner.cs
> +
А почему не заменить лист на какой-то осознанный класс, чтобы не пришлось вот так неочевидно сплитить?

2021-10-30 18:29 UTC, FrediKats commented on Kysect.CentumFramework.Utility/Fields/Factories/Assigner.cs
> +
![image](https://user-images.githubusercontent.com/22368203/139553709-a309b4cd-eda8-4dfd-913c-b4d45dfb3794.png)
Гит говорит, что тут лишний таб

2021-10-30 18:29 UTC, FrediKats commented on Kysect.CentumFramework.Utility/Fields/Factories/Assigner.cs
> +            var complexFieldAttribute = destination.GetCustomAttribute<ComplexFieldAttribute>();
Что это? И почему оно юзается только в проверке на null и всё?

2021-10-30 18:29 UTC, FrediKats commented on Kysect.CentumFramework.Utility/Fields/Factories/Assigner.cs
> +                typeof(TInnerTarget),
А тебе точно нужно явно передавать typeof? Ты же можешь внутри из дженерика вывести его.

2021-10-30 18:29 UTC, FrediKats commented on Kysect.CentumFramework.Utility/Fields/Attributes/FieldAttribute.cs
> +            JsonGoogleField = char.ToLower(googleField[0]) + googleField[1..];
А вот в нулевой лабе это решалось лучше...

2021-10-30 18:29 UTC, FrediKats commented on Kysect.CentumFramework.Utility/Fields/Attributes/ConvertableFieldAttribute.cs
> +                ? AccessCache.Function(_converterType, _methodName)(instance, new[] { value }).ThrowIfNull(nameof(value))
Не понятно что и как. Особенно в конце бросание эксепшена. Мы же проверили, что не null, а потом кинем, что он null, хотя не он.

2021-10-30 19:01 UTC, ronimizy commented on Kysect.CentumFramework.Utility/Fields/Factories/Assigner.cs
> +                .Select(From);
Да, так как оно дальше идёт только в метод, где он единожды вычисляется. Эта операция может быть достаточно затратной, так что не хотелось бы выполнять её до всех соответствующих проверок.

2021-10-30 19:12 UTC, ronimizy commented on Kysect.CentumFramework.Utility/Fields/Factories/Assigner.cs
> +            var complexFieldAttribute = destination.GetCustomAttribute<ComplexFieldAttribute>();
Это атрибут-флаг. Он информирует о том, что свойство хранит в себе экземпляр комплексного типа, типа внутри которого так же есть свойства к которым можно составить ассайнеры. 
Зарефакторю чтобы оно использовалось явно в определении аргументов конструктора.

2021-10-30 19:15 UTC, ronimizy commented on Kysect.CentumFramework.Utility/Fields/Factories/Assigner.cs
> +                typeof(TInnerTarget),
Рили

2021-10-30 19:34 UTC, ronimizy commented on Kysect.CentumFramework.Utility/Fields/Factories/Assigner.cs
> +                .ThrowIfNull(nameof(innerExpressions))
Это будет частью переноса на 10 шарпы, когда он наступит

2021-11-06 19:18 UTC, xrem approved these changes
Пацан залупу на отсечение поставил, говорит что все отлично и ничего не упадёт.

2021-11-07 11:35 UTC, FrediKats approved these changes
Надеюсь, пришивать потом будет не больно.

2021-11-07 11:55 UTC, merged